#!/bin/bash
mkdir ../out

#extract consensus single copy region
for i in `cat bamlist` ; do bash consensus.sh $i ; done
for i in `cat select.samplelist` ; do cat ../out/${i}.scy.fa ; done > select.scy.fa

#filters
python fastafilter.py \
       --infasta scy.fa \
       --keep male.list \
       --missind 0.8 \
       --misssite 0.5 \
       --biallelic \
       --singleton | fold -w80 > male.scy.b.s.fa

#ml tree
raxml-ng --all --msa male.scy.b.s.fa --model GTR+G --threads 4 --bs-trees 100

#modelgenerator and beast, xml file is generated by BEAUTi
java -jar modelgenerator.jar male.scy.b.s.fa 4
beast -overwrite -threads 8 $XML
